spring.application.name=lawsathi-backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/lawsathi
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# We are using Flyway
spring.jpa.hibernate.ddl-auto=none

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
